### ISSUE TITLE
Does it work with Bresser 3in1 as well?

### ISSUE THREAD

**Issue by iz3man** [matthias-bs/BresserWeatherSensorReceiver#122]
Sorry, found no other place to ask. I only saw version 5in1 6in1 7in1 mentioned, but there is a Wind/Temp/Humidity sensor from Bresser as well. Is this supported? Wanted to be sure before I start building.

Thanks!

https://www.amazon.de/dp/B07PDQCY7Q?psc=1&ref=ppx_yo2ov_dt_b_product_details

![image](https://github.com/matthias-bs/BresserWeatherSensorReceiver/assets/11553674/93dc90be-ffcc-4c1b-a11f-fa781338cbc7)

**Comment by matthias-bs** [comment]
Hi,

No problem. Yes, it is supported. You can find a list of supported devices in the table at the top of the [README]( https://github.com/matthias-bs/BresserWeatherSensorReceiver/blob/main/README.md).

Best regards
Matthias

**Comment by iz3man** [comment]
Danke dir! Thank you!

**Comment by iz3man** [comment]
closed
