### ISSUE TITLE
Radio sleep before ESP deep sleep to lower Power drain

### ISSUE THREAD

**Issue by mothra78** [matthias-bs/BresserWeatherSensorReceiver#125]
Great code now installed on Heltech Wireless Stick V3. When sleeping Stick still drains 10mA.
It seems SX1262 radio is still runnning

I added a simple sleep function that I call at the beginning of the sleep routine in loop() :

void WeatherSensor::sleep(void)
{
radio.sleep();
}

This brings the power down by a factor 10!

If you think this is usefull you might want to add it to the main branch

**Comment by matthias-bs** [comment]
Thank you for the hint! I already prepared the `sleep()` method, but I did not add it to the examples yet.
