### ISSUE TITLE
Compile Error if _DEBUG_MODE_   is used

### ISSUE THREAD

**Issue by franki29** [matthias-bs/BresserWeatherSensorReceiver#13]
Hi, if you enable _DEBUG_MODE_   in WeatherSensorCfg.h , you get a compile error at:

WeatherSensor.cpp:692:21: error: 'chksum' was not declared in this scope
  692 |         DEBUG_PRINT(chksum, HEX);
      |                     ^~~~~~

As you disable it in the code:
  // Checksum, add with carry
    // unused...
    **//int chksum = msg[17];**

Br. Frank

**Comment by matthias-bs** [comment]
Hi,

fixed in https://github.com/matthias-bs/BresserWeatherSensorReceiver/commit/5f38bca1d0c98a799d53467987f9d5f56e27f1d1

Cheers
Matthias
