### ISSUE TITLE
rain implementation -> renew examples

### ISSUE THREAD

**Issue by tonbor** [matthias-bs/BresserWeatherSensorReceiver#144]
the domoticz example is not correct (any more) because of new implementation of rain calculation
String(weatherSensor.sensor[i].w.rain_mm * 100, 1); should be rain mm per hour
domo2_payload = String("{"idx":") + String(DOMO_RAIN_IDX) + String(","nvalue":0,"svalue":"") + String(rainGauge.pastHour() * 100, 1);

if (weatherSensor.sensor[i].w.rain_ok)
{
domo2_payload = String("{"idx":") + String(DOMO_RAIN_IDX) + String(","nvalue":0,"svalue":"") + String(weatherSensor.sensor[i].w.rain_mm * 100, 1);
domo2_payload += String(";") + String(weatherSensor.sensor[i].w.rain_mm, 1);
domo2_payload += String(""}");
Serial.printf("%s: %s\n", MQTT_PUB_DOMO, domo2_payload.c_str());
client.publish(MQTT_PUB_DOMO, domo2_payload.c_str(), false, 0);
}

**Comment by matthias-bs** [comment]
Do you have an example of how the MQTT payload is supposed to look like - or even better - a link to the Domoticz specification?
I don't use this myself, I just implemented this upon a user's request.

**Comment by tonbor** [comment]
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Rain

Op di 19 mrt. 2024 18:00 schreef Matthias Prinke ***@***.***>:

**Comment by matthias-bs** [comment]
Can you please test it?
https://github.com/matthias-bs/BresserWeatherSensorReceiver/blob/fix-domoticz-rain/examples/BresserWeatherSensorDomoticz/BresserWeatherSensorDomoticz.ino

**Comment by matthias-bs** [comment]
Added in https://github.com/matthias-bs/BresserWeatherSensorReceiver/pull/152
