### ISSUE TITLE
Lightning sensor need pairing

### ISSUE THREAD

**Issue by simonsh** [matthias-bs/BresserWeatherSensorReceiver#184]
Can I use this sensor with this code without the requisite station base unit? It can be paired to a base unit (I don't have the supported model) but it is available individually?

**Comment by simonsh** [comment]
It arrives tomorrow on a Prime day, so happy to send any debug data I can get, if it helps. Let me know. I am on a Mac with a TTGO LoRa-32 OLED board.

**Comment by matthias-bs** [comment]
Yes, you can use all supported sensors without pairing and without a matching base station. The code uses all sensors which can be received unless you apply any of the include/exclude filters.

**Comment by simonsh** [comment]
Thanks for your prompt reply! I'll check on it tomorrow.

**Comment by simonsh** [comment]
It works fine. Mobile phones set it off for testing. Now zeroed and waiting for a storm :-) Will calibrate later at the same time as I work on the rain gauge. Keep up your excellent work.

**Comment by matthias-bs** [comment]
Thanks for the nice feedback!
