### ISSUE TITLE
Do I need to uncomment SENSOR_TYPE_AIR_PM?

### ISSUE THREAD

**Issue by simonsh** [matthias-bs/BresserWeatherSensorReceiver#186]
Do I need to uncomment SENSOR_TYPE_AIR_PM anywhere. The sensor arrives next week, thanks!

**Comment by matthias-bs** [comment]
No, non-existing sensors won't cause any problems.

**Comment by simonsh** [comment]
It will exist when I set it up next week.

**Comment by matthias-bs** [comment]
I expect it will work, because I am using it, too.

**Comment by simonsh** [comment]
OK, I now have a 5-in-1 weather station (new version), lightning sensor and PM AQ sensor. All working and your code is picking them up perfectly.
When I have made some more progress with my improved 7" ESP-S3 display, I will post a photo. Good work!

**Comment by matthias-bs** [comment]
That's great!

**Comment by matthias-bs** [comment]
You are right, the code size could be reduced by enabling/disabling parts of the 7-in-1 decoder. On the other hand, I don't want to make the configuration even more complicated than it already is.
