### ISSUE TITLE
AQ sensor reports 1.0PM

### ISSUE THREAD

**Issue by simonsh** [matthias-bs/BresserWeatherSensorReceiver#188]
Is this correct, as the sensor only advertises 2.5 PM and 10 PM? I know that 2.5PM is officially <= 2.5 PM.

**Comment by matthias-bs** [comment]
Yes, I think so. Please see https://github.com/matthias-bs/BresserWeatherSensorReceiver/issues/97.

**Comment by simonsh** [comment]
Looks like it, have you decoded PM4 yet?

Sensirion SPS-30

Particulate matter
--
Mass concentration precision | ±10 | % |  
Mass concentration range | 0 - 1000 | μg/m³ |  
Lifetime | > 10 | years |  
Particle size range | PM1.0, PM2.5, PM4 and PM10

**Comment by matthias-bs** [comment]
As I wrote in https://github.com/matthias-bs/BresserWeatherSensorReceiver/issues/97, there is one additional PM value in the radio message, which must be either PM1.0 or PM4. After comparison with the internal sensor signals (UART), I came to the conclusion that it is PM1.0 - but maybe I was wrong.

**Comment by simonsh** [comment]
If it is a similar reading to PM 2.5 then it is PM 1.0 but not if higher. I think you are correct and I will keep an eye on my log. Hasn’t gone over 2.5 so far even when PM 10 is higher. Will let you know.

**Comment by matthias-bs** [comment]
Please follow up in #97 if required.
