### ISSUE TITLE
Setting hostname on ESP8266 and ESP32 differs

### ISSUE THREAD

**Issue by kroon040** [matthias-bs/BresserWeatherSensorReceiver#19]
Hi,

I have solved why in the default code setting the hostname on esp8266 is not working.

On esp32 this is required setting the hostname must before de WiFi.mode()

    WiFi.hostname(Hostname);
    WiFi.mode(WIFI_STA);

On the esp8266 it must be turn around

    WiFi.mode(WIFI_STA);
    WiFi.hostname(Hostname);

So maybe it can be done in the code to check the board and to the right order.

**Comment by matthias-bs** [comment]
Hi,
Thank you for finding this out! I will change the code accordingly!

I wish the APIs of ESP32 and ESP8266 were better aligned...

Best regards
Matthias

**Comment by matthias-bs** [comment]
Added in https://github.com/matthias-bs/BresserWeatherSensorReceiver/commit/194380b2cdf74ea74f039653ace812a26c5bb763

**Comment by matthias-bs** [comment]
Hi,

can this issue be closed?

Thanks and regards
Matthias
