### ISSUE TITLE
Send data to mysql

### ISSUE THREAD

**Issue by asanbus** [matthias-bs/BresserWeatherSensorReceiver#196]
Would you mind add "Send to mysql"

Thank you

**Comment by asanbus** [comment]
Would you mind create ino? 
My system containt:
-TTGO LORA32 OLED 868
-Bresser 7-1
-BME280
-Mysql

**Comment by asanbus** [comment]
Data delay one minute

**Comment by asanbus** [comment]
It is imposible for me, Error and Error

Thank you

**Comment by asanbus** [comment]
![Captura de pantalla 2024-11-07 195319](https://github.com/user-attachments/assets/480697c3-55b0-4dbd-892a-f4d49815a6a2)

**Comment by matthias-bs** [comment]
I suggest to make yourself familiar with some common rules regarding getting support on GitHub. For instance, there are some forms for creating an issue in this project which indicate which kind of information is required to understand a problem.

You cannot expect that a volunteer reads your mind, solves your issues or develops an entirely customized software for you.

**Comment by asanbus** [comment]
Price?
