### ISSUE TITLE
VEVOR 7in1 Weather Station supported?

### ISSUE THREAD

**Issue by Nusserdt** [matthias-bs/BresserWeatherSensorReceiver#213]
I bought a [VEVOR Profi WLAN-Wetterstation 7-in-1](https://www.vevor.de/wetterstation-c_12074/vevor-profi-wlan-wetterstation-7-in-1-solarbetrieben-wettercenter-7-5-zoll-display-150m-uebertragungsreichweite-aussensensor-fuer-windgeschwindigkeit-windrichtung-temperatur-luftfeuchtigkeit-niederschlag-p_010713421113) and I am pretty unhappy that I can't receive my data locally (and integrate them to Home Assistant).

I was able to sniff the traffic with my fritzbox:

![image](https://github.com/user-attachments/assets/adabca5d-3ef3-4522-ab29-55f0014bd0b7)

so I know the data is available in my network in clear text, but at this point, I don't know how to read them. :-(

`/v01/set/wid/****/key/**********/bar/10131/temp/47/hum/94/wdir/230/wspd/28/dew/38/chill/20/heat/47/rainrate/0/rain/0/uvi/0/solarrad/147 HTTP/1.1 `

**Comment by matthias-bs** [comment]
Unless your sensor uses one of the Bresser protocol variants, it is out of this project's scope. Maybe a project like https://github.com/raphv/bresser-home-assistant is closer to what you are looking for.
