### ISSUE TITLE
Basic-Example gets data correctly, Mqtt-Example gets radom data?

### ISSUE THREAD

**Issue by mexxBf** [matthias-bs/BresserWeatherSensorReceiver#36]
**Describe the bug**

after a lot of fiddeling I got my rtm95w working. If I upload the basic example I can se the data its receiving is changing, e.g. the wind direction. But after uploading the Mqtt example I only get random? data? The data is not changing if I spin the anemometer, or change the wind direction by hand.

The data looks like the following:

`ESPWeather-925BA3/data/ 1234567: {"id":01234567,"battery_ok":1,"temp_c":22.2,"humidity":55,"wind_gust":4.4,"wind_avg":3.3,"wind_dir":111.1}
ESPWeather-925BA3/extra: {"wind_dir_txt":"ESE","wind_gust_bft":3,"wind_avg_bft":2,"dewpoint_c":12.7,"perceived_temp_c":24.8}`

has this something to do with the "num-sensors" and the mapping?

**To Reproduce**
I only changed my mqtt and wifi credentials. 

**Expected behavior**
Getting the data into my mqtt server just like I can see them with the basic-example

**Debug Log**
If applicable, add log file to help explain your problem.

**Embedded Device (please complete the following information):**
 - Board: Wemos mini
 - Arduino Version: 2.0.3
 - Library Version latest?

I guess I'm just missing a little thing...

Thank you

**Comment by matthias-bs** [comment]
Hi,

I'm pretty sure you have uncommented `_DEBUG_MQTT_`:

```
// Enable to debug MQTT connection; will generate synthetic sensor data.
//#define _DEBUG_MQTT_
```
Just leave it as a comment (as above) and you should see your real sensor data.

Best regards
Matthias
