### ISSUE TITLE
5-in-1 and 6-in-1 Decoder fail after PR #40

### ISSUE THREAD

**Issue by matthias-bs** [matthias-bs/BresserWeatherSensorReceiver#45]
@jorgenavarroortiz: The 6-in-1 decoder fails with "Digest check failed" after integrating https://github.com/matthias-bs/BresserWeatherSensorReceiver/pull/40.

**Comment by matthias-bs** [comment]
In decodeBresser7In1Payload(), the "data whitening" modifies the payload buffer in-place, rendering it useless for subsequent decoding attempts.

@jorgenavarroortiz Please make a local copy of the payload buffer (strongly preferred) or move this decoder to the end of the chain.

**Comment by matthias-bs** [comment]
Workaround: Comment out `#define BRESSER_7_IN_1` in https://github.com/matthias-bs/BresserWeatherSensorReceiver/blob/e69774b7375aecbde922bf0d078055341a8e7fec/src/WeatherSensorCfg.h#L216.

**Comment by jorgenavarroortiz** [comment]
Hi! I have submit a pull request. I have made a local copy of the payload buffer. It works with my weather station (7-in-1). Please test it with the other weather stations (5-in-1 and 6-in-1), it should work.

**Comment by matthias-bs** [comment]
Looks good! I'll check it tomorrow!
