### ISSUE TITLE
ESP keeps disconnecting

### ISSUE THREAD

**Issue by meijer3** [matthias-bs/BresserWeatherSensorReceiver#51]
When I reset the wifi, (or kill the power of the house...) the esp won't reconnect by it self. I need to power reset the ESP 

PS. Thanks alot for this code. It saves alot of coding time

**Comment by matthias-bs** [comment]
Hi,
Which example sketch are you referring to?
Actually the intended behaviour (of the MQTTexample) is that it tries to reconnect automatically.
Regards
Matthias

**Comment by meijer3** [comment]
That would be the `MQTTCustom`. I might have another look at my setup if you say it would reconnect. Thanks for the response
