### ISSUE TITLE
Add external raw data input

### ISSUE THREAD

**Issue by sgtJohnny** [matthias-bs/BresserWeatherSensorReceiver#72]
Because of an exposed location, my Arduino received a lot of other Bresser Stations or just junk data, which led to a longer wait time to get a "complete" message and i wanted the data as precise as possible. Since my indoor display got all the messages, I 'v built a "sniffer" circuit into the indoor display unit to grab the data from the built-in module.

I modified the code of the library to add a function to just provide the raw message, and have it decoded by the library.
Maybe this code could be added to the library as a new function:

```
 DecodeStatus WeatherSensor::decodeFromExternal(uint8_t* msg,uint8_t msgSize)
 {

    DecodeStatus    decode_res = DECODE_INVALID;

    #ifdef BRESSER_6_IN_1
               decode_res = decodeBresser6In1Payload(&msg[0], sizeof(msg) - 1);
    #endif
    #ifdef BRESSER_5_IN_1
        if (decode_res == DECODE_INVALID ||
            decode_res == DECODE_PAR_ERR ||
            decode_res == DECODE_CHK_ERR || 
            decode_res == DECODE_DIG_ERR) {
                decode_res = decodeBresser5In1Payload(&msg[1], sizeof(msg) - 1);
            }
    #endif
    return decode_res;
}
```

**Comment by matthias-bs** [comment]
Yes, I will add this. It is also useful for passing data to the decoder for testing.
