### ISSUE TITLE
Support of BME280

### ISSUE THREAD

**Issue by franki29** [matthias-bs/BresserWeatherSensorReceiver#8]
Hi, me again, sorry.
It would be also nice to add BME280 support to have also in house data.
Please find attached a very dirty hack again for supporting BME280.
[BresserWeatherSensorDomoticz_example.zip](https://github.com/matthias-bs/BresserWeatherSensorReceiver/files/9381596/BresserWeatherSensorDomoticz_example.zip)

![grafik](https://user-images.githubusercontent.com/36134288/185604628-f0cc124b-4709-44f3-81ed-292a4bb4b322.png)

It is tricky using a ESP8266 because of limited GPIO's, but at my side it is working with a wemos nodemcu clone device
Br Frank

**Comment by matthias-bs** [comment]
Hi,
sorry to say this, but this is clearly out of scope. I think it's time for your own fork. You seem to have a solution (at least partly) already - please let me know if you need help.
Best regards
Matthias

P.S.: I'm using the BME280 in my flora2 project. Nice little devices, but the rise in prices over the last months makes you dizzy...

**Comment by franki29** [comment]
OK, thanks for information.
Br. Frank
